basePath: /api
definitions:
  ledger.Balance:
    properties:
      account:
        type: string
      balance:
        type: string
    type: object
  main.Error:
    properties:
      message:
        type: string
    type: object
  main.File:
    properties:
      children:
        items:
          $ref: '#/definitions/main.File'
        type: array
      name:
        type: string
      path:
        type: string
      type:
        type: string
    type: object
  model.Account:
    properties:
      amount:
        type: number
      commodity:
        type: string
      name:
        type: string
    type: object
  model.Transaction:
    properties:
      accounts:
        items:
          $ref: '#/definitions/model.Account'
        type: array
      date:
        type: string
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /balances:
    get:
      consumes:
      - application/json
      description: get balances for a user
      parameters:
      - in: query
        name: begin
        type: string
      - in: query
        name: command
        type: string
      - in: query
        name: end
        type: string
      - in: query
        name: keyword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns user balances
          schema:
            items:
              $ref: '#/definitions/ledger.Balance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: Get Balances
      tags:
      - balances
  /files:
    get:
      consumes:
      - application/json
      description: get file list for a user
      produces:
      - application/json
      responses:
        "200":
          description: Returns user file list
          schema:
            items:
              $ref: '#/definitions/main.File'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: Get File List
      tags:
      - files
  /files/{path}:
    get:
      consumes:
      - application/json
      description: get file for a user
      parameters:
      - description: File Path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns user file
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: Get File
      tags:
      - files
  /templates:
    get:
      consumes:
      - application/json
      description: get templates for a user
      produces:
      - application/json
      responses:
        "200":
          description: Returns user templates
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: Get Templates
      tags:
      - templates
  /txs:
    get:
      consumes:
      - application/json
      description: get transactions for a user
      parameters:
      - in: query
        name: begin
        type: string
      - in: query
        name: command
        type: string
      - in: query
        name: end
        type: string
      - in: query
        name: keyword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns user transactions
          schema:
            items:
              $ref: '#/definitions/model.Transaction'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: Get Transactions
      tags:
      - transactions
    post:
      consumes:
      - application/json
      description: create a new transaction
      parameters:
      - description: Transaction Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: Returns new transaction
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.Error'
      summary: New Transaction
      tags:
      - transactions
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
